version: '2'
services:
  leeroy:
    image: jamorin/leeroy-java-microservice
    environment:
    - "SPRING_APPLICATION_NAME=leeroy"
    - "SERVER_SERVLET_CONTEXT_PATH=/leeroy"
    ports:
    - "8081:8080"
  jenkins:
    image: jamorin/leeroy-java-microservice
    environment:
    - "SPRING_APPLICATION_NAME=jenkins"
    - "SERVER_SERVLET_CONTEXT_PATH=/jenkins"
    ports:
    - "8082:8080"
  foobar:
    image: jamorin/leeroy-java-microservice
    environment:
    - "SPRING_APPLICATION_NAME=foobar"
    - "SERVER_SERVLET_CONTEXT_PATH=/foobar"
    ports:
    - "8083:8080"